### ISSUE TITLE
Add light/dark theme toggle

### ISSUE THREAD

**Issue by jasonbra1n** [jasonbra1n/astronomy#2]
Create Pull Request to add theme toggle functionality with the following changes:

1. Create new file `theme.js`
2. Update `styles.css` to add theme support
3. Update `index.html` to add theme toggle button and script reference

### New file: theme.js
```javascript
// Theme toggle functionality
document.addEventListener('DOMContentLoaded', () => {
    const themeToggle = document.getElementById('themeToggle');
    
    // Check for saved theme preference, otherwise use device preference
    const savedTheme = localStorage.getItem('theme') || 
        (window.matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark');
    
    // Apply the initial theme
    document.documentElement.setAttribute('data-theme', savedTheme);
    
    // Update button text based on current theme
    const updateButtonText = (theme) => {
        themeToggle.innerHTML = `${theme === 'light' ? '🌙' : '☀️'} Toggle Theme`;
    };
    
    updateButtonText(savedTheme);
    
    // Toggle theme
    themeToggle.addEventListener('click', () => {
        const currentTheme = document.documentElement.getAttribute('data-theme');
        const newTheme = currentTheme === 'light' ? 'dark' : 'light';
        
        // Update theme
        document.documentElement.setAttribute('data-theme', newTheme);
        localStorage.setItem('theme', newTheme);
        
        // Update button text
        updateButtonText(newTheme);
    });
});
```

### Update styles.css
Add at the beginning of the file:
```css
/* Light theme variables */
html[data-theme="light"] {
    --bg-color: #f0f2f5;
    --text-color: #1a1a2e;
    --section-bg: #ffffff;
    --input-bg: #e8eaed;
    --button-bg: #e94560;
    --button-text: #ffffff;
    --highlight-bg: #f5f5ff;
    --card-bg: #ffffff;
    --card-border: #e0e0e0;
    --accent: #e94560;
}

/* Dark theme variables (existing) */
html[data-theme="dark"] {
    --bg-color: #1a1a2e;
    --text-color: #e0e0e0;
    --section-bg: #16213e;
    --input-bg: #0f3460;
    --button-bg: #e94560;
    --button-text: #ffffff;
    --highlight-bg: #21214a;
    --card-bg: #23234a;
    --card-border: #30305a;
    --accent: #f9d923;
}

/* Theme toggle button styles */
.theme-toggle {
    position: absolute;
    top: 20px;
    right: 20px;
    background-color: var(--card-bg);
    color: var(--text-color);
    border: 1px solid var(--card-border);
    padding: 8px 16px;
    border-radius: 20px;
    cursor: pointer;
    font-size: 0.9em;
    transition: all 0.3s ease;
}

.theme-toggle:hover {
    background-color: var(--highlight-bg);
    border-color: var(--accent);
}

/* Add transition for theme changes */
body * {
    transition: background-color 0.3s ease, color 0.3s ease, border-color 0.3s ease;
}

@media (max-width: 600px) {
    .theme-toggle {
        position: relative;
        top: 0;
        right: 0;
        margin: 10px auto;
        display: block;
    }
}
```

### Update index.html
1. Add `data-theme="dark"` to the html tag:
```html
<html lang="en" data-theme="dark">
```

2. Add theme toggle button after the h1 in header:
```html
<header>
  <h1>✨ Astronomy Information</h1>
  <button id="themeToggle" class="theme-toggle" aria-label="Toggle light/dark mode">
    🌓 Toggle Theme
  </button>
</header>
```

3. Add theme.js script reference before closing body tag:
```html
<script src="astronomy.browser.js"></script>
<script src="script.js"></script>
<script src="theme.js"></script>
</body>
```

## Implementation Steps:
1. Create new file `theme.js` with the provided code
2. Update `styles.css` by adding the new theme variables and styles at the beginning of the file
3. Update `index.html`:
   - Add `data-theme="dark"` to the html tag
   - Add theme toggle button in header
   - Add theme.js script reference

## Testing:
1. Verify the theme toggle button appears in the header
2. Test theme switching:
   - Click toggle button to switch between light and dark themes
   - Verify colors update appropriately
   - Verify theme persists after page reload
3. Test responsive design:
   - Verify button position adjusts on mobile screens
4. Test system preference:
   - Verify initial theme matches system preference if no saved preference exists
